name: Run Coverage Report

on: [push]

jobs:
  test:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out your repository
      - name: Generate coverage report
      - run: nmp install # Install dependencies
      - run: npm run test # Get coverage
      - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
